[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
clap = {version = "4.5.42", features = ["derive"] }
pulldown-cmark = "0.13.0"
maud = "0.27.0"
serde = "1.0.228"
csv = "1.4.0"
rocket = "0.5.1"
